aula25/config/routes.rb
Rails.application.routes.draw do
  get "welcome/index"
  root "welcome#index"
  resources :occupations
  resources :children
  resources :fathers
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

aula25/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

aula25/app/models/child.rb
class Child < ApplicationRecord
  belongs_to :father
end

aula25/app/models/father.rb
class Father < ApplicationRecord
    has_many :children
    belongs_to :occupation
    has_one_attached :avatar

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    def occupation_description
        if self.occupation.blank?
            " - "
        else
            self.occupation.description
        end
    end

    has_one_attached :avatar do |attachable|
    attachable.variant :thumb, resize_to_limit: [300, 300]
    end
end

aula25/app/models/occupation.rb
class Occupation < ApplicationRecord
end

aula25/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

aula25/app/controllers/children_controller.rb
class ChildrenController < ApplicationController
  before_action :set_child, only: %i[ show edit update destroy ]

  # GET /children or /children.json
  def index
    @children = Child.all
  end

  # GET /children/1 or /children/1.json
  def show
  end

  # GET /children/new
  def new
    @child = Child.new
    @fathers = Father.all
  end

  # GET /children/1/edit
  def edit
    @fathers = Father.all
  end

  # POST /children or /children.json
  def create
    @child = Child.new(child_params)

    respond_to do |format|
      if @child.save
        format.html { redirect_to @child, notice: "Child was successfully created." }
        format.json { render :show, status: :created, location: @child }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /children/1 or /children/1.json
  def update
    respond_to do |format|
      if @child.update(child_params)
        format.html { redirect_to @child, notice: "Child was successfully updated." }
        format.json { render :show, status: :ok, location: @child }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @child.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /children/1 or /children/1.json
  def destroy
    @child.destroy!

    respond_to do |format|
      format.html { redirect_to children_path, status: :see_other, notice: "Child was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_child
      @child = Child.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def child_params
      params.expect(child: [ :name, :sex, :father_id ])
    end
end

aula25/app/controllers/fathers_controller.rb
class FathersController < ApplicationController
  before_action :set_father, only: %i[ show edit update destroy ]
  before_action :set_occupation, only: %i[ new create edit update ]


  # GET /fathers or /fathers.json
  def index
    @fathers = Father.all
    @father = Father.first
  end

  # GET /fathers/1 or /fathers/1.json
  def show
  end

  # GET /fathers/new
  def new
    @father = Father.new
  end

  # GET /fathers/1/edit
  def edit
  end

  # POST /fathers or /fathers.json
  def create
    @father = Father.new(father_params)

    respond_to do |format|
      if @father.save
        format.html { redirect_to @father, notice: "Father was successfully created." }
        format.json { render :show, status: :created, location: @father }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fathers/1 or /fathers/1.json
  def update
    respond_to do |format|
      if @father.update(father_params)
        format.html { redirect_to @father, notice: "Father was successfully updated." }
        format.json { render :show, status: :ok, location: @father }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @father.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fathers/1 or /fathers/1.json
  def destroy
    @father.destroy!

    respond_to do |format|
      format.html { redirect_to fathers_path, status: :see_other, notice: "Father was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_father
      @father = Father.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def father_params
      params.expect(father: [ :name, :cpf, :email, :occupation_id, :avatar ])
    end

    def set_occupation
      @occupations = Occupation.all
    end
end

    

aula25/app/controllers/occupations_controller.rb
class OccupationsController < ApplicationController
  before_action :set_occupation, only: %i[ show edit update destroy ]

  # GET /occupations or /occupations.json
  def index
    @occupations = Occupation.all
  end

  # GET /occupations/1 or /occupations/1.json
  def show
  end

  # GET /occupations/new
  def new
    @occupation = Occupation.new
  end

  # GET /occupations/1/edit
  def edit
  end

  # POST /occupations or /occupations.json
  def create
    @occupation = Occupation.new(occupation_params)

    respond_to do |format|
      if @occupation.save
        format.html { redirect_to @occupation, notice: "Occupation was successfully created." }
        format.json { render :show, status: :created, location: @occupation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /occupations/1 or /occupations/1.json
  def update
    respond_to do |format|
      if @occupation.update(occupation_params)
        format.html { redirect_to @occupation, notice: "Occupation was successfully updated." }
        format.json { render :show, status: :ok, location: @occupation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @occupation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /occupations/1 or /occupations/1.json
  def destroy
    @occupation.destroy!

    respond_to do |format|
      format.html { redirect_to occupations_path, status: :see_other, notice: "Occupation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_occupation
      @occupation = Occupation.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def occupation_params
      params.expect(occupation: [ :description ])
    end
end

aula25/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

aula25/app/helpers/application_helper.rb
module ApplicationHelper
    def sexo(sex)
        html = ""
        if sex == 'M'
        html = "Masculino"
        elsif sex == 'F'
        html = "Feminino"
        end

        html
    end
end

aula25/app/helpers/children_helper.rb
module ChildrenHelper
end

aula25/app/helpers/fathers_helper.rb
module FathersHelper
end

aula25/app/helpers/occupations_helper.rb
module OccupationsHelper
end

aula25/app/helpers/welcome_helper.rb
module WelcomeHelper
end

aula25/app/views/children/_child.html.erb
<div id="<%= dom_id child %>">
  <p>
    <strong>Name:</strong>
    <%= child.name %>
  </p>

  <p>
    <strong>Sex:</strong>
    <%= child.sex %>
  </p>

  <p>
    <strong>Father:</strong>
    <%= child.father.name %>
  </p>

</div>

aula25/app/views/children/_form.html.erb
<%= form_with(model: child) do |form| %>
  <% if child.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(child.errors.count, "error") %> prohibited this child from being saved:</h2>

      <ul>
        <% child.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :sex %><br>
    <%= select(:child, :sex,  options_for_select([["Masculino", "M"], ["Feminino", "F"]]), {include_blank: true}) %>
  </div>

  <div>
    <%= form.label :father_id, style: "display: block" %>
    <%= form.collection_select(:father_id, @fathers, :id, :name, {include_blank: true}) %>
  </div>
  <br>
  <div>
    <%= form.submit %>
  </div>
<% end %>

aula25/app/views/children/edit.html.erb
<% content_for :title, "Editing child" %>

<h1>Editing child</h1>

<%= render "form", child: @child %>

<br>

<div>
  <%= link_to "Show this child", @child %> |
  <%= link_to "Back to children", children_path %>
</div>

aula25/app/views/children/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Children" %>

<h1>Children</h1>

<div id="children">
  <% @children.each do |child| %>
    <%= render child %>
    <p>
      <%= link_to "Show this child", child %>
    </p>
  <% end %>
</div>

<%= link_to "New child", new_child_path %>

aula25/app/views/children/new.html.erb
<% content_for :title, "New child" %>

<h1>New child</h1>

<%= render "form", child: @child %>

<br>

<div>
  <%= link_to "Back to children", children_path %>
</div>

aula25/app/views/children/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @child %>

<div>
  <%= link_to "Edit this child", edit_child_path(@child) %> |
  <%= link_to "Back to children", children_path %>

  <%= button_to "Destroy this child", @child, method: :delete %>
</div>

aula25/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Aula25" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

aula25/app/views/occupations/_form.html.erb
<%= form_with(model: occupation) do |form| %>
  <% if occupation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(occupation.errors.count, "error") %> prohibited this occupation from being saved:</h2>

      <ul>
        <% occupation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

aula25/app/views/occupations/_occupation.html.erb
<div id="<%= dom_id occupation %>">
  <p>
    <strong>Description:</strong>
    <%= occupation.description %>
  </p>

</div>

aula25/app/views/occupations/edit.html.erb
<% content_for :title, "Editing occupation" %>

<h1>Editing occupation</h1>

<%= render "form", occupation: @occupation %>

<br>

<div>
  <%= link_to "Show this occupation", @occupation %> |
  <%= link_to "Back to occupations", occupations_path %>
</div>

aula25/app/views/occupations/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Occupations" %>

<h1>Occupations</h1>

<div id="occupations">
  <% @occupations.each do |occupation| %>
    <%= render occupation %>
    <p>
      <%= link_to "Show this occupation", occupation %>
    </p>
  <% end %>
</div>

<%= link_to "New occupation", new_occupation_path %>

aula25/app/views/occupations/new.html.erb
<% content_for :title, "New occupation" %>

<h1>New occupation</h1>

<%= render "form", occupation: @occupation %>

<br>

<div>
  <%= link_to "Back to occupations", occupations_path %>
</div>

aula25/app/views/occupations/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @occupation %>

<div>
  <%= link_to "Edit this occupation", edit_occupation_path(@occupation) %> |
  <%= link_to "Back to occupations", occupations_path %>

  <%= button_to "Destroy this occupation", @occupation, method: :delete %>
</div>

aula25/app/views/welcome/index.html.erb
<h1>Welcome!!!</h1>
<p><%= link_to "Fathers", fathers_path %></p>
<p><%=  link_to "Children", children_path %></p>
<p><%= link_to "Occupations", occupations_path %></p>